name: vs-benchmark
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - torch --index-url https://download.pytorch.org/whl/cu121
      - torchmetrics
      - lpips
      - torch-fidelity
      - Pillow
      - numpy